language: node_js
sudo: false

addons:
  sauce_connect:
    # Update SAUCE_USERNAME / SAUCE_ACCESS_KEY in travis if necessary
    # https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings
    # TODO: reenable saucelabs once we have update browser tests
    # sauce_connect: true

cache:
  timeout: 1000
  directories:
    - $HOME/.npm

env:

  matrix:
  - NODE_VER=8 FULL_VALIDATE=true
  - NODE_VER=8 TSC_VERSION=2.8.*
  - NODE_VER=8 TSC_VERSION=next
  - NODE_VER=9
  - NODE_VER=9 TSC_VERSION=2.8.*
  - NODE_VER=9 TSC_VERSION=next
  - NODE_VER=10
  - NODE_VER=10 TSC_VERSION=2.8.*
  - NODE_VER=10 TSC_VERSION=next

matrix:
  fast_finish: true
  allow_failures:
    - NODE_VER=8 TSC_VERSION=2.8.*
    - NODE_VER=8 TSC_VERSION=next
    - NODE_VER=9 TSC_VERSION=2.8.*
    - NODE_VER=9 TSC_VERSION=next
    - NODE_VER=10 TSC_VERSION=2.8.*
    - NODE_VER=10 TSC_VERSION=next

before_install:
  - nvm install $NODE_VER
  - npm install -g npm@6 && node -v && npm -v

install:
  - npm ci
  - if [ "$FULL_VALIDATE" == "true" ]; then npm run lint && npm run dtslint && npm run test:circular; fi

script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - if [ "$FULL_VALIDATE" == "true" ] && [ -n "DANGER_GITHUB_API_TOKEN" ]; then echo {} > ./.babelrc && npx danger; fi
  - npm test
  - npm run test:systemjs
  - if [ "${TSC_VERSION}" ]; then npm install --no-save typescript@$TSC_VERSION && ./node_modules/.bin/tsc --version && npm run build_cjs ; fi
  - if [ "$FULL_VALIDATE" == "true" ] && [ -n "DANGER_GITHUB_API_TOKEN" ]; then cd docs_app && npm ci && npm run build && cd ..; fi

after_success:
  - if [ "$FULL_VALIDATE" == "true" ]; then npm run test:cover && npx nyc report --reporter=text-lcov | npx coveralls; fi
  - if [ "$FULL_VALIDATE" == "true" ]; then npm run tests2png && cd docs_app && chmod 755 scripts/deploy-to-firebase.sh && npm run deploy-production; fi
